### ISSUE TITLE
better

### ISSUE THREAD

**Issue by critiqalfish** [jjonojj/typewriterbot#1]
`let preventPercent=80;let errors=0;let errorKey='#';document.getElementsByClassName("ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-dialog-buttons ui-resizable")[0].children[1].children[0].innerText="Drücke \""+document.getElementById("text_todo_1").children[0].innerText+"\" zum Starten";window.addEventListener("keydown",function(event){if(event.key==document.getElementById("text_todo_1").children[0].innerText||event.key==' '&&document.getElementById("text_todo_1").children[0].innerHTML=='&nbsp;'){console.log("congratulations! you pressed: "+event.key+" that was right 😊");}else if(event.key==errorKey){console.log("made an intentional error 😅");}else if(Math.random()*100<=preventPercent){event.stopImmediatePropagation();event.preventDefault();errors++;console.log(errors+" errors prevented 😎");}},{capture:true});`

der is guat für prüfungen. anfoch in de konsole pasten nachdemsd in da übung drin bist. kannst einstellen wie oft fehler machst oder anfoch intentional errors machen mit an key.

https://gist.github.com/critiqalfish/5a84d41f0169d8b038313816c0ea70b8

liabe grüsse aus da 2AHIF

**Comment by jjonojj** [comment]
whoa danke :)
